[platformio]
src_dir = Core/Src
include_dir = Core/Inc

[env:genericSTM32F411CE]
platform = ststm32
board = genericSTM32F411CE
framework = stm32cube
upload_protocol = dfu
monitor_speed = 115200

build_flags =
    -DSTM32F411xE
    -DUSE_HAL_DRIVER
    -DHSE_VALUE=8000000U
    -ICore/Inc
    -Wl,-u,_printf_float

build_src_filter =
    +<*>
    -<system_stm32f1xx.c>